global using Telegraph;
global using Humanizer;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Telegraph.DomainModels;
global using System.Reflection;
global using Telegraph.Persistence;
global using Telegraph.Services;
global using Telegraph.Contracts;